export const librosBiblia = [
    { name: 'Toda la Biblia', code: 1 },
    { name: 'Antiguo Testamento', code: 2 },
    { name: 'Nuevo testamento', code: 3 },
    { name: 'Génesis', code: 4 },
    { name: 'Éxodo', code: 5 },
    { name: 'Levítico', code: 6 },
    { name: 'Números', code: 7 },
    { name: 'Deuteronomio', code: 8 },
    { name: 'Josué', code: 9 },
    { name: 'Jueces', code: 10 },
    { name: 'Rut', code: 11 },
    { name: '1 Samuel', code: 12 },
    { name: '2 Samuel', code: 13 },
    { name: '1 Reyes', code: 14 },
    { name: '2 Reyes', code: 15 },
    { name: '1 Crónicas', code: 16 },
    { name: '2 Crónicas', code: 17 },
    { name: 'Esdrás', code: 18 },
    { name: 'Nehemías', code: 19 },
    { name: 'Tobías', code: 20 },
    { name: 'Judit', code: 21 },
    { name: 'Ester', code: 22 },
    { name: '1 Macabeos', code: 23 },
    { name: '2 Macabeos', code: 24 },
    { name: 'Job', code: 25 },
    { name: 'Salmos', code: 26 },
    { name: 'Proverbios', code: 27 },
    { name: 'Eclesiastés', code: 28 },
    { name: 'Cantar de los cantares', code: 29 },
    { name: 'Sabiduría', code: 30 },
    { name: 'Eclesiástico', code: 31 },
    { name: 'Isaías', code: 32 },
    { name: 'Jeremías', code: 33 },
    { name: 'Lamentaciones', code: 34 },
    { name: 'Baruc', code: 35 },
    { name: 'Ezequiel', code: 36 },
    { name: 'Daniel', code: 37 },
    { name: 'Oseas', code: 38 },
    { name: 'Joel', code: 39 },
    { name: 'Amós', code: 40 },
    { name: 'Abdías', code: 41 },
    { name: 'Jonás', code: 42 },
    { name: 'Miqueas', code: 43 },
    { name: 'Nahún', code: 44 },
    { name: 'Habacuc', code: 45 },
    { name: 'Sofonías', code: 46 },
    { name: 'Ageo', code: 47 },
    { name: 'Zacarías', code: 48 },
    { name: 'Malaquías', code: 49 },
    { name: 'Mateo', code: 50 },
    { name: 'Marcos', code: 51 },
    { name: 'Lucas', code: 52 },
    { name: 'Juan', code: 53 },
    { name: 'Hechos de los apóstoles', code: 54 },
    { name: 'Romanos', code: 55 },
    { name: '1 Corintios', code: 56 },
    { name: '2 Corintios', code: 57 },
    { name: 'Gálatas', code: 58 },
    { name: 'Efesios', code: 59 },
    { name: 'Filipenses', code: 60 },
    { name: 'Colosenses', code: 61 },
    { name: '1 Tesalonicenses', code: 62 },
    { name: '2 Tesalonicenses', code: 63 },
    { name: '1 Timoteo', code: 64 },
    { name: '2 Timoteo', code: 65 },
    { name: 'Tito', code: 66 },
    { name: 'Filemón', code: 67 },
    { name: 'Hebreos', code: 68 },
    { name: 'Santiago', code: 69 },
    { name: '1 Pedro', code: 70 },
    { name: '2 Pedro', code: 71 },
    { name: '1 Juan', code: 72 },
    { name: '2 Juan', code: 73 },
    { name: '3 Juan', code: 74 },
    { name: 'Judas', code: 75 },
    { name: 'Apocalipsis', code: 76 },

];